version: '3.4'

x-default:
  &default-odoo
  tty: true
  build: .
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./vendor/it-projects/it-projects-llc-addons:/mnt/addons/private
    - ./config:/etc/odoo

services:
  odoo:
    << : *default-odoo
    depends_on:
      - db
      - proxy
      - odoo-longpolling
      - smtpfake
    command: ['--dev', 'wdb,reload,qweb,werkzeug,xml',
    '-d', 'mr1_2021_02_16',
    '-i', 'sye_base,sye_contacts,sye_crm',
    '--load-language', 'ru_RU'
    ]

  odoo-longpolling:
    << : *default-odoo
    depends_on:
      - db
      - proxy
    command: ['odoo', 'gevent', '--dev', 'wdb,reload,qweb,werkzeug,xml']

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  proxy:
    image: envoyproxy/envoy-alpine:v1.10.0
    ports: ['80:80']
    volumes: ['./envoy.yaml:/etc/envoy/envoy.yaml']

  smtpfake:
    image: mailhog/mailhog

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
