version: '3.4'

x-default:
  &default-odoo
  tty: true
  build: .
  depends_on:
    - db
    - wdb
    - proxy
    - smtpfake
  ports:
    - "8069:8069"
    - "8072:8072"
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./config:/etc/odoo
    - ./vendor/it-projects-llc/mail-addons:/mnt/addons/mail-addons
    - ./vendor/it-projects-llc/pos-addons:/mnt/addons/pos-addons
    - ./vendor/it-projects-llc/sync-addons:/mnt/addons/sync-addons
    - ./vendor/it-projects-llc/website-addons:/mnt/addons/website-addons
    - ./vendor/OCA/pos:/mnt/addons/pos

  environment:
    - WDB_SOCKET_SERVER=wdb
    - WDB_NO_BROWSER_AUTO_OPEN=True


services:
  odoo:
    <<: *default-odoo
    command: ['--dev', 'wdb,reload,qweb,werkzeug,xml',
    '-d', 'openapi_test',
    '--init', 'openapi',
    '--log-handler=odoo.addons.openapi:DEBUG',
    ]

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  proxy:
    image: envoyproxy/envoy-alpine:v1.10.0
    ports: ['81:80', '80:80', '9901:9901']
    volumes: ['./envoy.yaml:/etc/envoy/envoy.yaml']
  wdb:
    image: kozea/wdb:3.3.0
    ports: ['1984:1984']
  smtpfake:
    image: mailhog/mailhog

volumes:
  odoo-web-data:
  odoo-db-data:
