version: '3.4'

x-default:
  &default-odoo
  tty: true
  image: my/odoo:13.0-suga
  depends_on:
    - db
    - wdb
    - proxy
    - mariadb
    - smtpfake
  ports:
    - "8069:8069"
    - "8072:8072"
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./config:/etc/odoo
    - ./vendor/eugene/private-bacula:/mnt/addons/private


  environment:
    - WDB_SOCKET_SERVER=wdb
    - WDB_NO_BROWSER_AUTO_OPEN=True

services:
  mariadb:
    image: mariadb:10.1.44
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sugarcrm_db
      MYSQL_USER: sugarcrm_user
      MYSQL_PASSWORD: sugarcrm_password
    ports: ['3306:3306']
    volumes: ['msql:/var/lib/mysql']

  odoo:
    << : *default-odoo
    command: ['--dev', 'wdb,reload,qweb,werkzeug,xml',
    '-d', 'suga',
    '--init', 'sugarodoo,sugarcrm_to_sugarodoo',
   '--log-handler=odoo.addons.sugarodoo:DEBUG',
   '--log-handler=odoo.addons.sugarcrm_to_sugarodoo:DEBUG',
    ]
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  proxy:
    image: envoyproxy/envoy-alpine:v1.10.0
    ports: ['81:80', '80:80', '9901:9901']
    volumes: ['./envoy.yaml:/etc/envoy/envoy.yaml']
  wdb:
    image: kozea/wdb:3.3.0
    ports: ['1984:1984']
  smtpfake: {image: mailhog/mailhog}


volumes:
  odoo-web-data:
  odoo-db-data:
  msql:
