version: '3.4'

x-default:
  &default-odoo
  tty: true
  build: .
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./vendor/odoo/odoo:/usr/lib/python3/dist-packages/odoo
    - ./vendor/odoo/addons:/var/lib/odoo/addons/12.0
    - ./config:/etc/odoo
    - ./vendor/it-projects-llc/mail-addons:/mnt/addons/mail-addons
    - ./vendor/it-projects-llc/pos-addons:/mnt/addons/pos-addons
    - ./vendor/it-projects-llc/sync-addons:/mnt/addons/sync-addons
    - ./vendor/it-projects-llc/website-addons:/mnt/addons/website-addons
    - ./vendor/OCA/pos:/mnt/addons/pos

services:
  odoo:
    << : *default-odoo
    depends_on:
      - db
      - proxy
      - odoo-longpolling
      - smtpfake
    command: [
    '-d', 'pos_debt_notebook',
    '-i', 'pos_debt_notebook',
#    '--test-enable', '--stop-after-init',
    '--log-handler=odoo.addons.pos_debt_notebook:DEBUG',
    ]

  odoo-longpolling:
    << : *default-odoo
    depends_on:
      - db
      - proxy
    command: ['odoo', 'gevent']

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  proxy:
    image: envoyproxy/envoy-alpine:v1.10.0
    ports: ['85:80']
    volumes: ['./envoy.yaml:/etc/envoy/envoy.yaml']

  smtpfake:
    image: mailhog/mailhog

volumes:
  odoo-web-data:
  odoo-db-data:
