version: '3.4'

x-default:
  &default-odoo
  tty: true
  build: .
  depends_on:
    - db
    - wdb
    - proxy
    - smtpfake
  ports:
    - "8069:8069"
    - "8072:8072"
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./config:/etc/odoo
    - ./vendor/it-projects-llc/saas-addons:/mnt/addons/saas-addons
    - ./vendor/it-projects-llc/access-addons:/mnt/addons/access-addons
    - ./vendor/OCA/web:/mnt/addons/web
    - ./vendor/OCA/queue:/mnt/addons/queue
    - ./vendor/OCA/server-auth:/mnt/addons/server-auth
    - ./vendor/OCA/contract:/mnt/addons/contract

  environment:
    - WDB_SOCKET_SERVER=wdb
    - WDB_NO_BROWSER_AUTO_OPEN=True
    - ODOO_QUEUE_JOB_HOST=saas.127.0.0.1.nip.io

services:
  dev:
    <<: *default-odoo
    command: ['--db-filter=.*']

  odoo:
    << : *default-odoo
    # TODO: unify parameter passing for different cases to avoid making different branches
    # '--db-filter=^%d$$' в этой записи если не экранировать $, то вызовет ошибку
    command: ['--dev', 'wdb,reload,qweb,werkzeug,xml', '-d', 'saas',
    '-i', 'saas_apps_signup,saas_access_apps',
    '--db-filter=^%d$$', '--load=web,queue_job',  '--workers=3',
              '--log-handler=odoo.addons.queue_job:DEBUG',
    ]
#'--log-handler=odoo.models:DEBUG',
#'--log-handler=odoo.addons.base.models.ir_cron:DEBUG',
#'--log-handler=odoo.modules.registry:DEBUG',
#'--log-handler=odoo.fields:DEBUG',
#'--log-handler=odoo.modules.loading:DEBUG',
#'--log-handler=odoo.addons.queue_job:DEBUG',
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  proxy:
    image: envoyproxy/envoy-alpine:v1.10.0
    ports: ['81:80', '80:80', '9901:9901']
    volumes: ['./envoy.yaml:/etc/envoy/envoy.yaml']
  wdb:
    image: kozea/wdb:3.3.0
    ports: ['1984:1984']
  smtpfake:
    image: mailhog/mailhog

volumes:
  odoo-web-data:
  odoo-db-data:
