version: '3.4'

x-default:
  &default-odoo
  tty: true
  build: .
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./vendor/odoo/odoo:/usr/lib/python3/dist-packages/odoo
    - ./vendor/odoo/addons:/var/lib/odoo/addons/12.0
    - ./config:/etc/odoo
#    - ./vendor/it-projects-llc/mail-addons:/mnt/addons/mail-addons
#    - ./vendor/it-projects-llc/odoo-saas-tools:/mnt/addons/odoo-saas-tools
#    - ./vendor/it-projects-llc/pos-addons:/mnt/addons/pos-addons
    - ./vendor/it-projects-llc/sync-addons:/mnt/addons/sync-addons
#    - ./vendor/it-projects-llc/website-addons:/mnt/addons/website-addons
#    - ./vendor/OCA/pos:/mnt/addons/pos
    - ./vendor/OCA/queue:/mnt/addons/queue

  environment:
    - WDB_SOCKET_SERVER=wdb
    - WDB_NO_BROWSER_AUTO_OPEN=True

services:
  odoo:
    << : *default-odoo
    depends_on:
      - db
#      - wdb
      - proxy
      - odoo-longpolling
#      - smtpfake
    command: ['--dev', 'wdb,qweb,werkzeug,xml',
    '-d', 'odinass',
    '-i', 'sync_1c',
#    '--test-enable', '--stop-after-init',
#    '--log-handler=odoo.addons.openapi:DEBUG',
    ]

  odoo-longpolling:
    << : *default-odoo
    depends_on:
      - db
#      - wdb
      - proxy
    command: ['odoo', 'gevent', '--dev', 'wdb,reload,qweb,werkzeug,xml']

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
#    ports:
#      - "5433:5432"

  proxy:
    image: envoyproxy/envoy-alpine:v1.10.0
    ports: ['6366:80']
    volumes: ['./envoy.yaml:/etc/envoy/envoy.yaml']

  wdb:
    image: kozea/wdb:3.3.0

  smtpfake:
    image: mailhog/mailhog

volumes:
  odoo-web-data:
  odoo-db-data:
