version: '3.4'

x-default:
  &default-odoo
  tty: true
  image: my/odoo:13.0-suga
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./vendor/odoo/odoo:/usr/lib/python3/dist-packages/odoo
    - ./vendor/odoo/addons:/var/lib/odoo/addons/13.0
    - ./config:/etc/odoo
    - ./vendor/eugene/private-bacula:/mnt/addons/private
    - ./vendor/enterprise:/mnt/addons/enterprise

  environment:
    - WDB_SOCKET_SERVER=wdb
    - WDB_NO_BROWSER_AUTO_OPEN=True

services:
  mariadb:
    image: mariadb:10.1.44
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sugarcrm_db
      MYSQL_USER: sugarcrm_user
      MYSQL_PASSWORD: sugarcrm_password
    ports: ['3306:3306']
    volumes: ['msql:/var/lib/mysql']

  odoo:
    << : *default-odoo
    depends_on:
      - db
      - wdb
      - proxy
      - smtpfake
      - odoo-longpolling
    command: ['--dev', 'wdb,reload,qweb,werkzeug,xml',
    '-d', 'suga2',
#    '-i', 'l10n_generic_coa,account_bank_statement_import_camt',
    '-u', 'bacula_account',
#    '--log-handler=odoo.addons.sugarodoo:DEBUG',
#    '--log-handler=odoo.addons.sugarcrm_to_sugarodoo:DEBUG',
#    '--test-enable', '--stop-after-init',
    ]

  odoo-longpolling:
    << : *default-odoo
    depends_on:
      - db
      - wdb
      - proxy
    command: ['odoo', 'gevent', '--dev', 'wdb,reload,qweb,werkzeug,xml']

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  proxy:
    image: envoyproxy/envoy-alpine:v1.10.0
    ports: ['80:80', '9901:9901']
    volumes: ['./envoy.yaml:/etc/envoy/envoy.yaml']

  wdb:
    image: kozea/wdb:3.3.0

  smtpfake:
    image: mailhog/mailhog

volumes:
  odoo-web-data:
  odoo-db-data:
  msql:
